### ISSUE TITLE
assign language to zipped repository project

### ISSUE THREAD

**Issue by jjaffres** [jjaffres/ghcnd_access#1]
My project language (code written entirely in Matlab/GNU Octave - language ID #225) is not recognised, possibly because the files are uploaded as a .zip file. How can the Matlab language label be added to my repository?

**Comment by gse-cc-git** [comment]
Hi @jjaffres. I'm just discovering your project via your publication. Great work, thanks for sharing !

As for the project language, I think you are right about the zipping avoiding automatic recognition of the coding language (see [this blog post](https://dev.to/katkelly/changing-your-repo-s-language-in-github-5gjo).

According to [this material](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml), the extension files recognised are `.m` or `.matlab` (no suprise here) so I suggest you add a `.m` sort of "readme file" and maybe a `.gitattributes` to your repo, (as mentioned in the first reference above) to somehow cheat/trick the language detector.

Best,
C.
